[pytest]
addopts = --import-mode=importlib -p no:cacheprovider
testpaths =
    cluster_manager/test/unit
    hcu-envcheck/tests
    hcu_resiliency_ext/tests
    hygon-ft-k8s/tests
    stack-analyzer/tests
pythonpath =
    cluster_manager
    hcu-envcheck
    hcu_resiliency_ext
    hygon-ft-k8s
    stack-analyzer
