# Copyright (c) 2026 Hygon Information Technology Co., Ltd.
# SPDX-License-Identifier: Apache-2.0
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: hygon-ft-pytorchjob-mutator
webhooks:
  - name: workload.ft.hygon.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 10
    objectSelector:
      matchExpressions:
        - key: ft.hygon.io/enabled
          operator: In
          values: ["true"]
    clientConfig:
      service:
        namespace: hygon-ft
        name: ft-webhook
        path: /mutate
        port: 443
      caBundle: __CA_BUNDLE__
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["kubeflow.org"]
        apiVersions: ["v1"]
        resources: ["pytorchjobs"]
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["batch.volcano.sh"]
        apiVersions: ["v1alpha1"]
        resources: ["jobs"]

